// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ7eUslBnOGgJkLxlU9P22N88PyC19SUI',
    appId: '1:856238791005:web:0a1edf416b8dbc36f2b0b4',
    messagingSenderId: '856238791005',
    projectId: 'student-commute-acfb9',
    authDomain: 'student-commute-acfb9.firebaseapp.com',
    storageBucket: 'student-commute-acfb9.appspot.com',
    measurementId: 'G-YGJWKX14YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN3RvtmY8Zepf--ENjTelilnXvXGUKMuU',
    appId: '1:856238791005:android:fb2830b6adf58ef1f2b0b4',
    messagingSenderId: '856238791005',
    projectId: 'student-commute-acfb9',
    storageBucket: 'student-commute-acfb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpwZxHs-_PrrSzB0YA_uGy6qiswDaY7w',
    appId: '1:856238791005:ios:69b6c246568395c3f2b0b4',
    messagingSenderId: '856238791005',
    projectId: 'student-commute-acfb9',
    storageBucket: 'student-commute-acfb9.appspot.com',
    iosBundleId: 'com.example.studentCommute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpwZxHs-_PrrSzB0YA_uGy6qiswDaY7w',
    appId: '1:856238791005:ios:69b6c246568395c3f2b0b4',
    messagingSenderId: '856238791005',
    projectId: 'student-commute-acfb9',
    storageBucket: 'student-commute-acfb9.appspot.com',
    iosBundleId: 'com.example.studentCommute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ7eUslBnOGgJkLxlU9P22N88PyC19SUI',
    appId: '1:856238791005:web:df17e5d93bcd6b9ff2b0b4',
    messagingSenderId: '856238791005',
    projectId: 'student-commute-acfb9',
    authDomain: 'student-commute-acfb9.firebaseapp.com',
    storageBucket: 'student-commute-acfb9.appspot.com',
    measurementId: 'G-249FPMEHR1',
  );
}
